### ISSUE TITLE
Device groups query is limited to 20 by default

### ISSUE THREAD

**Issue by sherbie** [Applifier/testdroid-ssa-client#10]
When using the -l param to list device groups, the maximum number of devices returned is 20. Here is a sample printout that shows what happens when there are more device groups than the limit allows:

],
  "limit": 20,
  "next": "https://cloud.testdroid.com/api/v2/users/74597015/device-groups?offset=20&limit=20&search=&sort=",
  "offset": 0,
  "previous": null,
  "search": "",
  "sort": "",
  "total": 22,
  "empty": false
}

**Comment by ujappelbe** [comment]
https://github.com/Applifier/testdroid-ssa-client/pull/15
