### ISSUE TITLE
Startup scripts should wait for appium to start rather than using hardcoded sleep

### ISSUE THREAD

**Issue by sherbie** [Applifier/testdroid-ssa-client#16]
There have often been failures caused by appium server not being ready to service test runs. Testdroid responded with this recommendation: "I would suggest to either add more sleep in between or add some check for the Appium process or the appium.log before initiating the session?"

This means we should either wait until appium.log exists or a pid is visible here:

https://github.com/Applifier/testdroid-ssa-client/blob/master/run-tests-android.sh#L15

and here:

https://github.com/Applifier/testdroid-ssa-client/blob/master/run-tests-ios.sh#L15

**Comment by sherbie** [comment]
I implemented a fix for this that will wait intelligently for 30 seconds for the server to start: https://github.com/Applifier/testdroid-ssa-client/pull/17

**Comment by shusso** [comment]
closing per #17
